# Copyright (c) 2023 Cisco and/or its affiliates.

# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at

#                https://developer.cisco.com/docs/licenses

# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# To create executable files locally
# first, install gorelease in your machine then use:
# goreleaser release --snapshot --rm-dist
# binaries will be available under dist dir 
---
project_name: catalyst-center_rna
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - rm -rf dist
    - go mod download
    - go test ./...
builds:
  - id: catalyst-center_rna
    binary: catalyst-center_rna
    main: ./
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - id: catalyst-center_rna
    rlcp: true
    format: zip
    files:
      - README.md
      - LICENSE
    name_template: >-
      catalyst-center-rna_{{ .Version }}_
      {{- if eq .Os "darwin" }}MacOS
      {{- else if eq .Os "windows" }}Windows
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "amd64" }}64-bit{{ end }}

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
